feat(site-builder): on publish raise an error when a file is empty (#117)
So far the `site-builder` was silently ignoring empty files.

This PR adds a check that raises an error when an empty file is included
in the directory that is to be published.
Also, the check should be done before trying to create a walrus blob id.

i.e. 
```shell
❯ ./target/release/site-builder --config site-builder/assets/builder-example.yaml publish examples/snake/

...
Parsing the directory examples/snake/ and locally computing blob IDs ...
Error during execution
Error: error while reading resource `examples/snake/empty.txt`

Caused by:
    0: Walrus sites does not support empty files.
    1: The file examples/snake/empty.txt is empty.
```

---------

Co-authored-by: giac-mysten <124184614+giac-mysten@users.noreply.github.com>